title: Alessandro Menti's website
email: alessandro.menti@alessandromenti.it
description: Putting theory into practice and vice versa
baseurl: ""
url: "https://www.alessandromenti.it"
twitter:
  username: AlessMenti
github:
  username: AlessandroMenti
linkedin:
  username: AlessandroMenti
social:
  name: Alessandro Menti
  links:
  - https://github.com/AlessandroMenti
  - https://twitter.com/AlessMenti
  - https://www.linkedin.com/in/AlessandroMenti

timezone: Europe/Rome
permalink: /blog/:year/:month/:title.html
author:
  name: "Alessandro Menti"
  twitter: AlessMenti
  github: AlessandroMenti

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-github-metadata
  - jekyll-sitemap
paginate: 5
paginate_path: "/blog/page:num"
defaults:
  - scope:
      path: "assets/**/*"
    values:
      sitemap: false
  - scope:
      path: "css/**/*"
    values:
      sitemap: false
  - scope:
      path: "downloads/**/*"
    values:
      sitemap: false
  - scope:
      path: "fonts/**/*"
    values:
      sitemap: false
  - scope:
      path: "images/**/*"
    values:
      sitemap: false
  - scope:
      path: "js/**/*"
    values:
      sitemap: false
exclude:
  - .bundle
  - Gemfile
  - Gemfile.lock
  - vendor
sass:
  sass_dir: _sass
  style: compressed
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
